---
title: "Kernel SVM"
author: "Heaven Klair"
date: "6/14/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Importing the dataset


```{r, echo=TRUE}
dataset = read.csv('Social_Network_Ads.csv')
Age = dataset$Age
EstimatedSalary = dataset$EstimatedSalary
Purchased = dataset$Purchased
```

## Splitting the dataset into the Training set and Test set

You can also embed plots, for example:

```{r, echo=TRUE}
library(caTools)
set.seed(123)
split = sample.split(dataset$Purchased, SplitRatio = 0.75)
training_set = subset(dataset, split == TRUE)
test_set = subset(dataset, split == FALSE)
```


## Feature Scaling

```{r, echo=TRUE}
training_set[-3] = scale(training_set[-3])
test_set[-3] = scale(test_set[-3])
```

## Fitting classifier to the Training set

```{r, echo=TRUE}
# install.packages(e1071)
library(e1071)
classifier = svm(formula = Purchased ~ .,
                 data = training_set,
                 type = 'C-classification',
                 kernel = 'radial')
```

## Predicting the Test set results

```{r, echo=TRUE}
y_pred = predict(classifier, newdata = test_set[-3])
```

## Making the Confusion Matrix

```{r, echo=TRUE}
cm = table(test_set[, 3], y_pred)
cm
```